// Compact ISO 3166-1 alpha-2 country list used by the Profile → Country field.
// Codes/names are standard public data, not tied to any single source.
const COUNTRIES = [
	{ code: 'IN', name: 'India' },
	{ code: 'US', name: 'United States' },
	{ code: 'GB', name: 'United Kingdom' },
	{ code: 'CA', name: 'Canada' },
	{ code: 'AU', name: 'Australia' },
	{ code: 'DE', name: 'Germany' },
	{ code: 'FR', name: 'France' },
	{ code: 'ES', name: 'Spain' },
	{ code: 'IT', name: 'Italy' },
	{ code: 'NL', name: 'Netherlands' },
	{ code: 'SE', name: 'Sweden' },
	{ code: 'NO', name: 'Norway' },
	{ code: 'DK', name: 'Denmark' },
	{ code: 'FI', name: 'Finland' },
	{ code: 'IE', name: 'Ireland' },
	{ code: 'PT', name: 'Portugal' },
	{ code: 'PL', name: 'Poland' },
	{ code: 'CH', name: 'Switzerland' },
	{ code: 'AT', name: 'Austria' },
	{ code: 'BE', name: 'Belgium' },
	{ code: 'BR', name: 'Brazil' },
	{ code: 'MX', name: 'Mexico' },
	{ code: 'AR', name: 'Argentina' },
	{ code: 'ZA', name: 'South Africa' },
	{ code: 'NG', name: 'Nigeria' },
	{ code: 'EG', name: 'Egypt' },
	{ code: 'AE', name: 'United Arab Emirates' },
	{ code: 'SA', name: 'Saudi Arabia' },
	{ code: 'IL', name: 'Israel' },
	{ code: 'TR', name: 'Turkey' },
	{ code: 'RU', name: 'Russia' },
	{ code: 'CN', name: 'China' },
	{ code: 'JP', name: 'Japan' },
	{ code: 'KR', name: 'South Korea' },
	{ code: 'SG', name: 'Singapore' },
	{ code: 'MY', name: 'Malaysia' },
	{ code: 'ID', name: 'Indonesia' },
	{ code: 'TH', name: 'Thailand' },
	{ code: 'VN', name: 'Vietnam' },
	{ code: 'PH', name: 'Philippines' },
	{ code: 'PK', name: 'Pakistan' },
	{ code: 'BD', name: 'Bangladesh' },
	{ code: 'LK', name: 'Sri Lanka' },
	{ code: 'NP', name: 'Nepal' },
	{ code: 'NZ', name: 'New Zealand' },
].sort( ( a, b ) => a.name.localeCompare( b.name ) );

export default COUNTRIES;
